### PR TITLE
fix: migration to new multiformats

### LINKED ISSUE #27: Update for compatibility with multiformats 4 configuration-free API
https://github.com/multiformats/js-multiformats/pull/36 rewrites the API of `multiformats` to avoid creating a central registrar object, but this module expects the now-defunct object as an argument to its constructor. This module will need to be rewritten either to import its own dependencies from `multiformats` or to consume them as arguments.

### PR DESCRIPTION
**Pull request by rvagg**
BREAKING CHANGE!

now `import { encode, decode } from '@ipld/dag-json'`

update README
add LICENSE files

Closes #27

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,53 +1,57 @@
...
+
+const decode = (buffer) => {
+  const obj = JSON.parse(bytes.toString(buffer))
+  return _decode({ value: obj }).value
 }
+
+const name = 'dag-json'
+const code = 0x0129
+
+export { encode, decode, name, code }
```
Comment (Gozala) [inline index.js:57]: I would suggest following instead:

```js
import { codec } from 'multiformats/codecs/codec'
export default codec({ name, code, encode, decode })
```

Because it will:

1. Create a codec that is implements both encoder and decoder ends
2. Expose `encoder` and `decoder` ends separately.
3. If we do end up adding some kind of contaminators, `dag-json` would automatically get that as well.

**Review by Gozala — COMMENTED** [review]
Looks great thanks for updating it @rvagg. My only concern is that this does not use provided `codec` function and just implements interface, so any changes made would need to be coordinated.

**Comment by Gozala** [comment]
Just got to the dag-pb PR where some of this was discussed. I posted a bit more justification to my position there https://github.com/ipld/js-dag-pb/pull/3#issuecomment-704741890
